export { default as Community } from "./view/Community";
export { default as CommunityDetail } from "./view/CommunityDetail";
export { default as CommunityPost } from "./view/CommunityPost";
export { default as Study } from "./view/Study";
export { default as StudyDetail } from "./view/StudyDetail";
export { default as StudyPost } from "./view/StudyPost";
export { default as Project } from "./view/Project";
export { default as ProjectDetail } from "./view/ProjectDetail";
export { default as ProjectPost } from "./view/ProjectPost";
